#!/usr/bin/env bash
# cairn-miner - HiveOS config generator. Sourced by the HiveOS agent; turns the
# flight-sheet fields into a cairn-miner config.toml. Deliberately robust: it
# reads the standard fields (%WAL% -> $CUSTOM_TEMPLATE, pool -> $CUSTOM_URL,
# extra args -> $CUSTOM_USER_CONFIG) and works whether the wallet is passed via
# the Wallet template OR via --address in Extra config args.
[[ -z $CUSTOM_CONFIG_FILENAME ]] && return
conf_dir=$(dirname "$CUSTOM_CONFIG_FILENAME")
mkdir -p "$conf_dir"

# Wallet: HiveOS substitutes %WAL% in the template to the real address, and may
# append a worker as address.worker - split it back out.
tmpl="${CUSTOM_TEMPLATE}"
addr="${tmpl%%.*}"
worker="${WORKER_NAME:-$(hostname)}"
[[ "$tmpl" == *.* ]] && worker="${tmpl#*.}"
addr="${addr#0x}"
# The miner requires lowercase hex and hard-rejects uppercase (a checksummed or
# copy-pasted address would otherwise crash-loop the rig). Normalize here.
addr="${addr,,}"

# Pool: default to the public cairn pool; strip any stratum+tcp:// prefix.
pool="${CUSTOM_URL:-cairn-pool.com:3333}"
pool="${pool#stratum+tcp://}"; pool="${pool#stratum://}"

{
  echo "# cairn-miner config (generated by HiveOS h-config.sh)"
  # Surface a blank wallet loudly: the miner refuses to start without a 40-hex
  # address, and a bare validation error is easy to miss in the miner log.
  [ -z "$addr" ] && echo "# WARNING: no wallet set (Wallet template empty and no --address in Extra config args) — the miner will not start until you set one."
  echo "address = \"$addr\""
  echo "pool = \"$pool\""
  echo "worker = \"$worker\""
  echo "cpu_threads = 0"
} > "$CUSTOM_CONFIG_FILENAME"

# Extra config args (backend, geometry, etc.) are passed straight to the binary
# by h-run.sh via CUSTOM_USER_CONFIG - nothing else to do here.
